apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-06-26T07:03:56Z
  generateName: corgran-ginx-7b5cd5697b-sd69m-
  labels:
    app: corgran-ginx
    pod-template-hash: "3617812536"
  name: corgran-ginx-7b5cd5697b-sd69m-9jkd4
  namespace: default
  resourceVersion: "42118"
  selfLink: /api/v1/namespaces/default/services/corgran-ginx-7b5cd5697b-sd69m-9jkd4
  uid: 17d7d325-790f-11e8-bc49-42010a9e006c
spec:
  clusterIP: 10.31.252.59
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-to-80-tcp
    nodePort: 30381
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 80-to-80-udp
    nodePort: 30381
    port: 80
    protocol: UDP
    targetPort: 80
  selector:
    app: corgran-ginx
    pod-template-hash: "3617812536"
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
